trigger: none        # do not auto-trigger on commits
pr: none             # do not auto-trigger on PRs

variables:
  AZURE_SERVICE_CONNECTION: 'azure-connection'         # name of Service Connection
  DOCKER_CONNECTION: 'dockerhub_connection'              # Docker Registry service connection
  dockerHubUsername: 'ahad8'                             # Docker Hub username
  IMAGE_NAME: 'frontend'                                 # repo name on Docker Hub
  TAG: '$(Build.BuildId)'                                # image tag based on build ID
  RESOURCE_GROUP:     'devops2-group3-main-rg'   # RG that contains AKS
  AKS_CLUSTER_NAME:   'devops2-group3-main-aks'  #  AKS cluster name
  K8S_DIR:            '../manifests/kubernetes'                        # path to K8s manifests
  NAMESPACE:          'capstone-project'   
     
pool:
  vmImage: 'ubuntu-latest'

stages:
# === Stage: Build & Push Image to Docker Hub ===
- stage: Build
  displayName: 'Build & Test & Push Frontend Image'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
      - checkout: self

      - task: SonarQubePrepare@5
        displayName: 'Prepare SonarQube Analysis'
        inputs:
          SonarQube: 'sonarqube-f-connection'      # اسم Service Connection
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'Authentication-Frontend'
          cliProjectName: 'Authentication Frontend'
          extraProperties: |
            sonar.projectBaseDir=authentication_app_frontend.gr3
            sonar.sources=.

      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '18.x'

      - script: |
          cd authentication_app_frontend.gr3
          npm install
          npm run build
        displayName: 'Build Frontend'

      - task: SonarQubeAnalyze@5
        displayName: 'Run SonarQube Analysis'

      - task: SonarQubePublish@5
        displayName: 'Publish SonarQube Results'
        inputs:
          pollingTimeoutSec: '300'

      - task: Docker@2
        displayName: 'Login to Docker Hub'
        inputs:
          containerRegistry: '$(DOCKER_CONNECTION)'
          command: login

      - task: Docker@2
        displayName: 'Build & Push to Docker Hub'
        inputs:
          containerRegistry: '$(DOCKER_CONNECTION)'
          repository: '$(dockerHubUsername)/$(IMAGE_NAME)'
          command: buildAndPush
          dockerfile: 'authentication_app_frontend.gr3/Dockerfile'
          buildContext: 'authentication_app_frontend.gr3'
          tags: |
            $(TAG)
  # === Stage: Deploy to AKS ===
- stage: Deploy
  displayName: 'Deploy Frontend to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Apply Kubernetes Manifests'
    steps:
      - checkout: self

      # Get AKS Credentials
      - task: AzureCLI@2
        displayName: 'Get AKS Credentials'
        inputs:
          azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az aks get-credentials \
              --resource-group $(RESOURCE_GROUP) \
              --name $(AKS_CLUSTER_NAME) \
              --admin \
              --overwrite-existing
            kubectl config current-context

      # 3)  apply Namespace
      - script: |
          kubectl apply -f $(K8S_DIR)/namespace.yml
        displayName: 'Apply Namespace'

      # 4)  Deployment + Service +delete old ingress if any and apply ingress
      - script: |
        
          kubectl apply -f $(K8S_DIR)/frontend_deploy.yml
          kubectl apply -f $(K8S_DIR)/frontend_cluster_ip.yml

          # delete old Ingress(if there's a one) to avoid conflict 
          kubectl delete ingress frontend-ingress -n $(NAMESPACE) || true

          # apply Ingress again
          kubectl apply -f $(K8S_DIR)/frontend_ingress.yml
        displayName: 'Apply Frontend Manifests'

