apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deploy
 labels:
   app: backend-app
 namespace: capstone-project
spec:
 replicas: 2
 selector:
   matchLabels:
     app: backend-app
 template:
   metadata:
     name: backend-app
     labels:
       app: backend-app
   spec:
     containers:
       - name: backend-app
         image: /backend:latest
         ports:
           - containerPort: 3000
         env:
           - name: DB_SERVER
             value: "" # Add Server name
           - name: DB_USER
             value: "" # Add Db user
           - name: DB_PASSWORD
             value: "" # Add Db pass
           - name: DB_NAME
             value: "" # Add Db name
