apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend-app
  namespace: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      name: frontend-app
      labels:
        app: frontend-app
    spec:  # 
      containers:
        - name: frontend-app
          image: ahad8/frontend:latest
          ports:
            - containerPort: 3000
